#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

source hooks/common.sh

hostmgmt_int=$(config-get hostmgmt_int)
uplink_profile=$(config-get uplink_profile)

cat > vsm-config-data <<EOF
export hostmgmt_int=$hostmgmt_int
export uplink_profile="$uplink_profile"
EOF

update-n1kv-config
