#!/bin/bash

source hooks/common.sh

# relation data
vsm_ip=$(relation-get vsm_ip)
vsm_domain_id=$(relation-get vsm_domain_id)

cat > vsm-relation-data <<EOF
export vsm_ip=$vsm_ip
export vsm_domain_id=$vsm_domain_id
EOF

update-n1kv-config
