#!/bin/bash

# relation data
vsm_ip=$(relation-get vsm_ip)
vsm_domain_id=$(relation-get vsm_domain_id)

# config data
#vsm_mgmt_int=$(config-get vsm_mgmt_int)


#echo $vsm_ip > /tmp/vsm-config
#echo $vsm_domain_id >> /tmp/vsm-config

#export vsm_ip
#export vsm_domain_id

cat > vsm-relation-data <<EOF
export vsm_ip=$vsm_ip
export vsm_domain_id=$vsm_domain_id
EOF
