#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

#apt-get install -y vem

cat > vsm-config-data <<EOF
export hostmgmt_int=eth1
export uplink_profile="default"
EOF

cat > vsm-relation-data <<EOF
export vsm_ip=10.0.0.1
export vsm_domain_id=1
EOF
